### ISSUE TITLE
Can not run objective-c demo

### ISSUE THREAD

**Issue by zhuangyz** [speechsuper/SpeechSuper-SDK-iOS#1]
Showing All Messages
Unknown file type in '/Users/xxx/Downloads/SpeechSuper-SDK-iOS-ObjectiveC-Demo-main/RecorderDemo/Speechsuper/libskegn.a'

**Comment by speechsuper** [comment]
This issue might be due to large files in our iOS SDK not downloading successfully. Please use `git lfs` to download the repo, as the .a files are quite large.
