### ISSUE TITLE
Error 20014 

### ISSUE THREAD

**Issue by zhuangyz** [speechsuper/SpeechSuper-SDK-iOS#2]
20014 | no provision profile | Ensure the existence of the 'skegn.provision' file.

What's skegn.provision?

**Comment by speechsuper** [comment]
You encountered this issue because you don't have access to our SDK free trial. Please check the `readme` file on how to get a free trial key for our SDK.

**Comment by zhuangyz** [comment]
I got the free trial key today.
Error show when start record.

<img width="254" alt="截屏2024-12-10 16 24 09" src="https://github.com/user-attachments/assets/6edfde9e-a1a2-4d24-bebb-6422fe141dbf">
<img width="263" alt="截屏2024-12-10 16 26 56" src="https://github.com/user-attachments/assets/e91e216d-5a53-4481-adec-2b63974e56ed">

**Comment by zhuangyz** [comment]
When running App, log:
LOG_ERROR |2024-12-10 16:10:35.823  config/sdkcfg/sdkcfg.cc#119 InitByPath() func:InitByPath(),open file failed....
LOG ([5.4.0~198-9cb5]:Collapse():nnet-utils.cc:1449) Added 1 components, removed 2

**Comment by speechsuper** [comment]
We didn't issue any SDK free trial key today. Please check if you're getting an **API free trial key** or an **SDK free trial key**.

**Comment by speechsuper** [comment]
We’ve checked your key, and it’s an API free trial key, not an SDK free trial key. For getting started with our API, please refer to this repo: [link](https://github.com/speechsuper/SpeechSuper-API-Samples)
